retrieve config via getenv, memcached and ldap extensions

diff --git a/files/etc/my_init.d/1_php b/files/etc/my_init.d/1_php
--- a/files/etc/my_init.d/1_php
+++ b/files/etc/my_init.d/1_php
@@ -6,39 +6,29 @@ if [ -f "$LOCK_FILE" ]; then
 	exit 0
 fi
 
-if [ ! -d /run/php ]; then
-	mkdir "/run/php"
-fi
-
-CONF_FILE=/opt/librenms/config.php
-CUSTOM_CONF_FILE=/opt/librenms/config.custom.php
-
-function addConfig() {
-	KEY="$1"
-	VALUE="$2"
-
-	if [ -n "$VALUE" ]; then
-		if grep -q "$KEY" "$CONF_FILE"; then
-			sed -i "s|.*$KEY.*|$KEY = '$VALUE';|g" "$CONF_FILE"
-		else
-			NON_ESCAPED_KEY=$(echo "$KEY" | tr -d '\\')
-			echo "$NON_ESCAPED_KEY = '$VALUE';" >> "$CONF_FILE"
-		fi
-	fi
+function requireConfig() {
+	if [ -z "$1" ]; then
+		echo "Error: $1 is unset"
+		exit 1
+    fi
 }
 
-addConfig "\$config\['db_host'\]" "$DB_HOST"
-addConfig "\$config\['db_user'\]" "$DB_USER"
-addConfig "\$config\['db_pass'\]" "$DB_PASS"
-addConfig "\$config\['db_name'\]" "$DB_NAME"
-addConfig "\$config\['memcached'\]\['enable'\]" "$MEMCACHED_ENABLE"
-addConfig "\$config\['memcached'\]\['host'\]" "$MEMCACHED_HOST"
-addConfig "\$config\['memcached'\]\['port'\]" "$MEMCACHED_PORT"
-addConfig "\$config\['base_url'\]" "$BASE_URL"
-addConfig "\$config\['update'\]" "$UPDATE"
+requireConfig DB_HOST
+requireConfig DB_USER
+requireConfig DB_PASS
+requireConfig DB_NAME
+requireConfig MEMCACHED_ENABLE
+requireConfig MEMCACHED_HOST
+requireConfig MEMCACHED_PORT
+requireConfig BASE_URL
+requireConfig UPDATE
 
-if [ -f "$CUSTOM_CONF_FILE" ]; then
-	cat "$CUSTOM_CONF_FILE" >> "$CONF_FILE"
+if [ -f /opt/librenms/config.custom.php ]; then
+	cat /opt/librenms/config.custom.php >> /opt/librenms/config.php
+fi
+
+if [ ! -d /run/php ]; then
+	mkdir /run/php
 fi
 
 touch "$LOCK_FILE"
