generate laravel .env on startup (issue #73), docs update

diff --git a/files/etc/my_init.d/4_config b/files/etc/my_init.d/4_config
--- a/files/etc/my_init.d/4_config
+++ b/files/etc/my_init.d/4_config
@@ -7,6 +7,7 @@ function requireConfig() {
 	fi
 }
 
+requireConfig APP_KEY
 requireConfig DB_HOST
 requireConfig DB_USER
 if [ -z "$DB_PASS_FILE" ]; then
@@ -15,6 +16,8 @@ fi
 requireConfig DB_NAME
 requireConfig BASE_URL
 
+set -eu
+
 if [ -f /opt/librenms/config.custom.php ]; then
 	echo -e "\033[1;33mWARNING: Detected deprecated config.custom.php file, please check the docs\033[0m" >&2
 
@@ -22,3 +25,10 @@ if [ -f /opt/librenms/config.custom.php ]; then
 	cat /opt/librenms/config.custom.php >> /opt/librenms/conf.internal.d/config.custom.php
 	chown librenms:librenms /opt/librenms/conf.internal.d/config.custom.php
 fi
+
+
+# Generate Laravel .env file from legacy config
+APP_ENV=local /sbin/setuser librenms composer run-script post-install-cmd -d /opt/librenms
+
+# Not deleting the directory causes validation errors in LibreNMS
+rm -rf /opt/librenms/.composer
